apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - name: "6200"
    port: 6200
    targetPort: 6200
  selector:
    io.kompose.service: backend
  type: LoadBalancer
status:
  loadBalancer: {}
