steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_backend', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_frontend', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

images: ['gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']
